### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mattcarter11**

### CODE REVIEW

**Comment by lolgeny** [comment]
Thanks - but please could you move the structure guide to the worldgen section?

**Comment by mattcarter11** [comment]
I don't see a worldgen section currently. Where should I move the structure guide then?

**Comment by mattcarter11** [comment]
I don't see a worldgen section currently. Where should I move the structure guide then?

**Comment by misode** [comment]
I think having it in the tutorials section makes sense, although they both need to be sorted alphabetically

**Comment by mattcarter11** [comment]
I have updated the added contents to be in alphabetically order

**Pull request closed without merging**
